baseURL = "https://castalio.info"
title = "Castálio Podcast"
copyright = "© 2011-{year} Castálio Podcast"
defaultContentLanguage = "pt-br"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^rst2html.py$']
